language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt update
  - sudo apt upgrade
  - sudo apt install sqlite3
install:
  - pip install -r requirements.txt
script:
  - tox